const state={leads:JSON.parse(localStorage.getItem("ach_leads")||"[]")};
const $=id=>document.getElementById(id);
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page).classList.add("active");$("title").textContent=b.textContent});
function openModal(){$("modal").classList.add("show")}function closeModal(){$("modal").classList.remove("show")}
$("add").onclick=openModal;$("close").onclick=closeModal;document.querySelector(".add").onclick=openModal;
$("form").onsubmit=e=>{e.preventDefault();state.leads.push({name:$("business").value.trim(),web:$("website").value.trim()||"—",score:+$("score").value,value:+$("potential").value||0});localStorage.setItem("ach_leads",JSON.stringify(state.leads));closeModal();e.target.reset();$("potential").value=500;render()};
$("save").onclick=()=>alert("Settings saved locally.");
function render(){const l=state.leads;$("total").textContent=l.length;$("hot").textContent=l.filter(x=>x.score>=75).length;$("msgs").textContent=l.length;$("value").textContent="$"+l.reduce((a,x)=>a+x.value,0).toLocaleString();$("rows").innerHTML=l.length?l.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.web)}</td><td>${x.score}/100</td><td>${x.score>=75?"Hot":"Warm"}</td><td>$${x.value.toLocaleString()}</td></tr>`).join(""):'<tr><td colspan="5" class="empty">No leads yet. Add your first prospect.</td></tr>';$("out").innerHTML=l.length?l.map(x=>`<div class="card outreachcard"><b>${esc(x.name)}</b><p>Hi ${esc(x.name)}, I came across your business and noticed an opportunity to improve the website experience. I build modern websites and web apps for businesses. If you're open to it, I can send a few specific ideas.</p></div>`).join(""):'<div class="card empty">No outreach drafts yet.</div>'}
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("install").classList.add("hidden")}};
if("serviceWorker"in navigator && location.protocol!=="file:"){navigator.serviceWorker.register("./sw.js").catch(console.error)}
render();
